### ISSUE TITLE
Constantly getting error while preset active

### ISSUE THREAD

**Issue by Schwegg** [kawaii/Moodles#13]
Constantly getting this error while any Preset is made
```
> [3/2/2024 2:09:21 PM -05:00] Object reference not set to an instance of an object.
   at Moodles.Gui.TabPresets.DrawSelected() in /home/runner/work/Moodles/Moodles/Moodles/Gui/TabPresets.cs:line 76
   at Moodles.Gui.TabPresets.Draw() in /home/runner/work/Moodles/Moodles/Moodles/Gui/TabPresets.cs:line 34
   at ECommons.ImGuiMethods.ImGuiEx.EzTabBar(String id, Boolean KoFiTransparent, ValueTuple`4[] tabs) in /home/runner/work/Moodles/Moodles/ECommons/ECommons/ImGuiMethods/ImGuiEx/ImGuiEx.cs:line 874
   at Moodles.Gui.UI.Draw() in /home/runner/work/Moodles/Moodles/Moodles/Gui/UI.cs:line 29
   at ECommons.GenericHelpers.Safe(Action a, Boolean suppressErrors) in /home/runner/work/Moodles/Moodles/ECommons/ECommons/GenericHelpers.cs:line 981
```
Along with this, while I'm not sure if tied to this error or not, but I'm also unable to see others' Moodles on the target bar and unable to apply Moodles to others.
![GIF 3-2-2024 2-14-16 PM](https://github.com/kawaii/Moodles/assets/34012814/a39c69a4-dde7-4dac-9e7c-d45894eac42a)

**Comment by kawaii** [comment]
Can you upload your plugin configuration please.

**Comment by Schwegg** [comment]
sadly I reset the plugin and now it seems to work fine without any errors. Sorry D:
