### ISSUE TITLE
Crashing when entering a crowded venue.

### ISSUE THREAD

**Issue by Lockehart** [kawaii/Moodles#19]
When entering a crowded venue with mostly paired people, majority having Moodles, a crash occurs.  I assume it happens when too many buffs are trying to be applied all at once.  Crashed 3 times on entering the same venue, crashes stopped when i disabled moodles.

Every single crash log had this in the dump info
Dump at: C:\Users\___\AppData\Roaming\XIVLauncher\dalamud_appcrash_20240302_204123_207_67796.dmp
System Time: 2024-03-03 01:41:23.9267710

   at Moodles.VfxManager.ActorVfx.Remove()
   at Moodles.VfxManager.VfxSpawn.Remove()
   at Moodles.VfxManager.VfxSpawn.Tick()
   at Moodles.Processors.CommonProcessor.Tick()
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act)
   at Dalamud.Utility.EventHandlerExtensions.InvokeSafely(OnUpdateDelegate updateDelegate, Framework framework)
   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework)

**Comment by kawaii** [comment]
@rootdarkarchon has pushed an update to [Mare Synchronos](https://github.com/Penumbra-Sync) that should hopefully resolve these crashes. Since I know you're an avid venue person please test and let me know if it happens again.
