### ISSUE TITLE
Debuffs on self playing no VFX or SFX

### ISSUE THREAD

**Issue by EminentEmily** [kawaii/Moodles#53]
As of latest patch no  VFX/SFX play when applying debuffs whatsoever; buffs still work as expected.

**Comment by Glyceri** [comment]
This is somewhat intended. By default it now uses the VFX that belongs with the icon. If you cast the doom icon on yourself it'll now use the doom VFX. However, some icons don't get any VFX. You can use the new custom VFX path setting to apply a VFX in that case.
<img width="465" alt="image" src="https://github.com/user-attachments/assets/4f77a067-2e0b-4df6-9eff-acd4dccc1391">

**Comment by Glyceri** [comment]
Are you getting an error log in /xllog? I've tried to make sure it prints errors when stuff goes wrong.

**Comment by heschlim** [comment]
It's been spamming my /xllog with this error about 20 times a second
`07:01:38.944 | ERR | Exception during raise of "Void <InvokeSafely>b__0()"
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at Moodles.Processors.CommonProcessor.Tick() in D:\a\Moodles\Moodles\Moodles\GameGuiProcessors\CommonProcessor.cs:line 133
	   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\\Utility\EventHandlerExtensions.cs:line 124
`

**Comment by Glyceri** [comment]
I think this has to do with something else.... HOOOAAGGHHH. This is probably why it is breaking VFX, ill have a look at it when I'm home😭

**Comment by EminentEmily** [comment]
Hello! So it seems that custom VFX works great when it comes to playing the VFX/SFX for debuffs. It only seems to not be playing when there's no custom VFX path set for the Moodle. I activated Debug mode and checked the log, and I saw this line which might be relevant? > [12/2/2024 7:29:48 PM -08:00] Path for SHE is empty

**Comment by Glyceri** [comment]
HMMMM, if the path is empty itll take path that belongs with the icon, sometimes those are empty. I think ill add a case where if the default path is empty we use the old vfx path as a backup later today.

**Comment by Glyceri** [comment]
This will be fixed in 2.0 c:
